
"""FastAPI application entry point."""

from fastapi import Depends, FastAPI, HTTPException, status
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from backend.app.database import Base, engine, get_db
from backend.app.security import hash_password
from backend.models.user import User
from backend.schemas.user_schema import UserRegisterRequest, UserRegisterResponse

# Create the FastAPI app instance used by Uvicorn and tests.
app = FastAPI(title="COSC310 Food Delivery API")


# Ensure required tables exist when the service starts.
@app.on_event("startup")
def on_startup() -> None:
    # Create ORM-mapped tables if they are missing.
    Base.metadata.create_all(bind=engine)


# Basic health endpoint for quick local readiness checks.
@app.get("/health")
def health_check() -> dict[str, str]:
    # Return a small status payload for monitoring.
    return {"status": "ok"}


# Register a new user account with username uniqueness enforcement.
@app.post(
    "/auth/register",
    response_model=UserRegisterResponse,
    status_code=status.HTTP_201_CREATED,
)
def register_user(payload: UserRegisterRequest, db: Session = Depends(get_db)) -> UserRegisterResponse:
    # Normalize whitespace to avoid accidental duplicates like "alice " vs "alice".
    normalized_username = payload.username.strip()

    # Reject registration if the username already exists.
    existing_user = db.query(User).filter(User.username == normalized_username).first()
    if existing_user is not None:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Username already exists.")

    # Build a new user entity with a hashed password and default non-manager role.
    new_user = User(
        username=normalized_username,
        hashed_password=hash_password(payload.password),
        is_manager=False,
    )
    db.add(new_user)

    try:
        # Persist the user to the database.
        db.commit()
    except IntegrityError:
        # Roll back failed transactions and return a duplicate-username error.
        db.rollback()
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Username already exists.") from None

    # Reload autogenerated values like id from the committed row.
    db.refresh(new_user)

    # Return a safe response that never includes password data.
    return UserRegisterResponse(
        id=new_user.id,
        username=new_user.username,
        is_manager=new_user.is_manager,
    )
