
"""FastAPI application entry point."""

from fastapi import Depends, FastAPI, Header, HTTPException, status
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from backend.app.database import Base, engine, get_db
from backend.app.security import hash_password
from backend.models.user import User
from backend.schemas.user_schema import UserRegisterRequest, UserRegisterResponse

# Create the FastAPI app instance used by Uvicorn and tests.
app = FastAPI(title="COSC310 Food Delivery API")


# Ensure required tables exist when the service starts.
@app.on_event("startup")
def on_startup() -> None:
    # Create ORM-mapped tables if they are missing.
    Base.metadata.create_all(bind=engine)


# Basic health endpoint for quick local readiness checks.
@app.get("/health")
def health_check() -> dict[str, str]:
    # Return a small status payload for monitoring.
    return {"status": "ok"}


# Resolve the current authenticated user from request headers for protected routes.
def get_current_user(
    x_user_id: int | None = Header(default=None, alias="X-User-Id"),
    db: Session = Depends(get_db),
) -> User:
    # Require caller identity on protected endpoints.
    if x_user_id is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Authentication required.")

    # Load the calling user from the database.
    current_user = db.query(User).filter(User.id == x_user_id).first()
    if current_user is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid user credentials.")

    # Return the authenticated user object to downstream dependencies/routes.
    return current_user


# Enforce manager-only access for administrative endpoints.
def require_manager(current_user: User = Depends(get_current_user)) -> User:
    # Reject users without manager privileges.
    if not current_user.is_manager:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Manager role required.")

    # Return the manager user when authorization succeeds.
    return current_user


# Register a new user account with username uniqueness enforcement.
@app.post(
    "/auth/register",
    response_model=UserRegisterResponse,
    status_code=status.HTTP_201_CREATED,
)
def register_user(payload: UserRegisterRequest, db: Session = Depends(get_db)) -> UserRegisterResponse:
    # Normalize whitespace to avoid accidental duplicates like "alice " vs "alice".
    normalized_username = payload.username.strip()

    # Reject registration if the username already exists.
    existing_user = db.query(User).filter(User.username == normalized_username).first()
    if existing_user is not None:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Username already exists.")

    # Derive manager flag from the requested account role.
    is_manager = payload.role == "manager"

    # Build a new user entity with a hashed password and assigned role.
    new_user = User(
        username=normalized_username,
        hashed_password=hash_password(payload.password),
        role=payload.role,
        is_manager=is_manager,
    )
    db.add(new_user)

    try:
        # Persist the user to the database.
        db.commit()
    except IntegrityError:
        # Roll back failed transactions and return a duplicate-username error.
        db.rollback()
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Username already exists.") from None

    # Reload autogenerated values like id from the committed row.
    db.refresh(new_user)

    # Return a safe response that never includes password data.
    return UserRegisterResponse(
        id=new_user.id,
        username=new_user.username,
        is_manager=new_user.is_manager,
        role=new_user.role,
    )


# Example protected endpoint accessible to any authenticated account.
@app.get("/portal/user")
def user_portal(current_user: User = Depends(get_current_user)) -> dict[str, str]:
    # Return user-facing content for both regular users and managers.
    return {"message": f"Welcome {current_user.username}. User portal access granted."}


# Example protected endpoint restricted to manager role.
@app.get("/portal/manager")
def manager_portal(current_user: User = Depends(require_manager)) -> dict[str, str]:
    # Return manager-only content after role check passes.
    return {"message": f"Welcome {current_user.username}. Manager portal access granted."}
